name: George Samartzopoulos
favicon: null
layout_spectrum: 0.6419
typography_spectrum: 0.74374
title: 'George Samartzopoulos | architecture & urbanism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64635f'
    - '#c9c8cd'
    - '#0c0a0d'
    - '#fbffff'
    - '#dc7216'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
