typography_spectrum: 0.74374
color:
  brandColors:
    - '#64635f'
    - '#c9c8cd'
    - '#0c0a0d'
    - '#fbffff'
    - '#dc7216'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: George Samartzopoulos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: MIXED USE DEVELOPMENT OFFICE & CULTURAL SPACES
    id: 85f56471-2f79-486e-a6bb-198175505776
    type: content
favicon: null
title: George Samartzopoulos | architecture & urbanism
description: ''
purpose: []
