name: gsamartzo
favicon: null
layout_spectrum: 0.7027264577336609
typography_spectrum: 0.10453803697600961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.012826921651139855
  lightness: 0.12618567841127515
  saturation: 0.9374612849205732
  rhythmicContrast: 0.3343580348882824
purpose: []
