typography_spectrum: 0.74374
color:
  brandColors:
    - '#64635f'
    - '#c9c8cd'
    - '#0c0a0d'
    - '#fbffff'
    - '#dc7216'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: George Samartzopoulos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: TV-Tower
    id: 5df6f4bd-6c5c-4dac-bf33-317b232f67b9
    type: content
  - name: City Home
    id: 75a8994a-b706-47e4-901d-f4f96c989db9
    type: content
  - name: Porto pool promenade
    id: 59a99e3d-8d65-43cb-bf91-19b1ee787e7c
    type: content
  - name: Transformable surface
    id: 2beabcb0-68ac-4fa2-838b-827d01ea21ae
    type: content
  - name: Liatang - Heung Yuen Wai boundary control point
    id: 3e48197f-3f57-4195-8981-aa70fb73f717
    type: content
  - name: Drosscape & the city the case of Eleonas - Athens
    id: 4b4ade36-72e9-4006-a5d9-70abdd00f591
    type: content
  - name: Re – Providence
    id: a7715fd6-b308-4db8-97c9-d4b13b18e58f
    type: content
  - name: Urban box
    id: de7f84a9-c5aa-45ee-81e1-710ce949ffb6
    type: content
  - name: Mixed use
    id: 5b15a48e-66cd-4457-a44d-33652f7c7892
    type: content
  - name: Mixed use development office & cultural spaces
    id: 85f56471-2f79-486e-a6bb-198175505776
    type: content
  - name: Elementary school
    id: 342eb5ef-5d8f-4151-8bce-077aeb683f1a
    type: content
favicon: null
title: architecture & urbanism portfolio
description: ''
purpose: []
